### ISSUE TITLE
Setting explicit xsi:type

### ISSUE THREAD

**Issue by isalento** [bhoriuchi/soap-connect#2]
When creating a vm,with a network card, the device type and backing object type needs to be set to certain values. By default "device" and "backing" objects are serialized to following XML elements.
<vim25:device xsi:type="vim25:VirtualDevice">
<vim25:backing xsi:type="vim25:VirtualDeviceDeviceBackingInfo">

Where as the correct format should be:
<vim25:device xsi:type="vim25:VirtualVmxnet3">
<vim25:backing xsi:type="vim25:VirtualEthernetCardNetworkBackingInfo">

Thanks to Branden, latest soap-connect already has support for setting xsi-type.
https://github.com/bhoriuchi/soap-connect/blob/38edd91e4bc0e5adedebec34a6309ee470ece968/src/client/serialize.js#L20-L25

However when using explicit xsi:type, an error is thrown:
```
TypeError: Cannot read property 'base' of undefined
    at serialize (C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1161:18)
    at C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1193:80
    at arrayEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:9359:14)
    at serialize (C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1169:5)
    at C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1193:80
    at arrayEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:9359:14)
    at serialize (C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1169:5)
    at C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1181:59
    at arrayMap (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:660:23)
    at Function.map (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:9571:14)
    at C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1175:45
    at arrayEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Projects\test\esxitest2\node_modules\lodash\lodash.js:9359:14)
    at serialize (C:\Projects\test\esxitest2\node_modules\soap-connect\index.js:1169:5)
```

Sample script to create VM
```javascript
let vm = await v.method("CreateVM_Task", {
        _this: dataCenter.vmFolder,        
        config: {
            name: vmSpec.name,            
            guestId: vmSpec.guestId,
            files: {
              vmPathName: `[${datastore.name}] ${vmSpec.name}/${vmSpec.name}.vmx`
            },
            version: vmSpec.version,
            memoryMB: vmSpec.memoryMB,
            numCPUs: vmSpec.numCPUs,
            deviceChange: [{                
                operation: 'add',
                device: {
                    '@xsi:type': 'vim25:VirtualVmxnet3',
                    backing: {
                        '@xsi:type': 'vim25:VirtualEthernetCardNetworkBackingInfo',
                        deviceName: 'VM Network',                        
                        useAutoDetect: true,
                        network: {
                            value: 'HaNetwork-VM Network',
                            type: 'Network'
                        }
                    },
                    connectable: {
                        connected: true,
                        startConnected: true,
                        allowGuestControl: true
                    },
                    deviceInfo: {
                        label: 'Network Adapter 1',
                        summary: 'VM Network'
                    },
                    key: 0,
                    addressType: 'generated',
                    wakeOnLanEnabled: true,                    
                    present: true
                },
            }]
        },
        pool: {
            type: "ResourcePool",
            value: "ha-root-pool"
        }        
    });
```

For me it looks like `wsdl.getType(typeCoord)` expects input as array of  indexes, but now it receives a string "vim25:VirtualVmxnet3".

**Comment by bhoriuchi** [comment]
Try the latest commit. i have update the typeMatch function with

```js
  if (_.isString(explicitType) && explicitType.indexOf(':') !== -1) {
    delete data[`@${XSI_PREFIX}:type`] // remove from the object
    return wsdl.getType(explicitType.split(':'))
  }
```

**Comment by bhoriuchi** [comment]
Try the latest commit. I have added a new helper function to `wsdl` to lookup typeCoord by prefix and localName and used that method in type match.

in wsdl
```js
  getTypeByLocalNSPrefix (nsPrefix, localName) {
    let nsIdx = _.findIndex(this.metadata.namespaces, { prefix: nsPrefix })
    let ns = _.get(this.metadata.namespaces, `[${nsIdx}]`)
    let typeIdx = ns.types.indexOf(localName)
    return [ nsIdx, typeIdx ]
  }
```

in typeMatch
```js
  if (_.isString(explicitType) && explicitType.indexOf(':') !== -1) {
    delete data[`@${XSI_PREFIX}:type`] // remove from the object
    return wsdl.getTypeByLocalNSPrefix(explicitType.split(':'))
  }
```

**Comment by isalento** [comment]
I had to make a small tweak in typeMatch to get it working. 
```javascript
function typeMatch(wsdl, type, data) {
  // check for an explicitly defined type and return it if found and remove it from the object
  var explicitType = _.get(data, '["@' + XSI_PREFIX + ':type"]');
  if (_.isString(explicitType) && explicitType.indexOf(':') !== -1) {
    delete data['@' + XSI_PREFIX + ':type']; // remove from the object
    var [nsPrefix, localName] = explicitType.split(':');
    return wsdl.getTypeByLocalNSPrefix(nsPrefix, localName);
  }
```
But after that it seems to work well and now VMs can be created with a network card. 
Thanks again 👍

**Comment by bhoriuchi** [comment]
nice catch! i have updated the build and pushed the commit. feel free to make any PR's you think are needed to this project or vsphere-connect.
